print('=== PADARIA DES VOS PYTHON! ===')
print('Olá! Seja bem vindo à: Padaria Des Vos Python!')
nome = input('Para começararmos, qual é seu nome? ')
print('Certo, bem vindo(a) '+nome)
print('Vou lhe passar o cardápio, certo?')
print('========= CARDÁPIO DES VON PYTHON: ================')
print('1 - "Café Especial Edition Java" - 25.99 PyMoney;')
print('2 - "Bolo Especial PHP" - 45.99 PyMoney;')
print('3 - "Refrigerante Ruby Language" - 15.99 PyMoney;')
print('4 - "Água de qualidade Perl" - 5.99 PyMoney;')
print('5 - "Bolachas C Language" - 25.99 PyMoney;')
print('===================================================')