print("== Cadastro da Escola ==")
nome = input('Digite o nome: ')
print('Bem vindo(a) '+nome)
lazer = input('O que você gosta de fazer? ')
print('Legal! Gostas de '+lazer)
cor = input('Qual a sua cor preferida? ')
print('Sua cor preferida então é '+cor)
time = input('Qual o seu time de futebol? ')
print ('Time do Coração: '+time)
filme = input('Qual é o seu filme preferido? ')
print ('Legal! Seu filme favorito então é: '+filme)