print('=== PADARIA DES VOS PYTHON! ===')
print('Olá! Seja bem vindo à: Padaria Des Vos Python!')
nome = input('Para começararmos, qual é seu nome? ')
print('Certo, bem vindo(a) '+nome)
print('Vou lhe passar o cardápio, certo?')
print('========= CARDÁPIO DES VOS PYTHON: ================')
print('1 - "Café Especial Edition Java" - 25 PyMoney;')
print('2 - "Bolo Especial PHP" - 45 PyMoney;')
print('3 - "Refrigerante Ruby Language" - 15 PyMoney;')
print('4 - "Água de qualidade Perl" - 5 PyMoney;')
print('5 - "Bolachas C Language" - 25 PyMoney;')
print('===================================================')

produto = input('Qual produto você deseja comprar? ')
preco = int(input('Qual o preço desse produto? (Ex: 25) '))
quantidade = int(input('Quantos você vai querer? '))

total = preco * quantidade

print('===== RESUMO DO PEDIDO =====')
print('Cliente: ' + nome)
print('Produto: ' + produto)
print('Preço unitário: ' + str(preco) + ' PyMoney')
print('Quantidade: ' + str(quantidade))
print('Total a pagar: ' + str(total) + ' PyMoney')
print('============================')
